//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by FastGenericNew.SourceGenerator
//     Please do not modify this file directly
// <auto-generated/>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Diagnostics.CodeAnalysis;
using System.Reflection;
using System.Reflection.Emit;
using System.ComponentModel;

namespace @FastGenericNew
{
	internal 
#if NETFRAMEWORK
static partial class FastNew<
#if NET5_0_OR_GREATER
[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicParameterlessConstructor | DynamicallyAccessedMemberTypes.NonPublicConstructors)]
#endif
T>
    {
#if NETFRAMEWORK
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        internal static readonly bool _isValueTypeT = typeof(T).IsValueType;
#endif
		/// <summary>
		/// The constructor of <typeparamref name="T" /> with given arguments. <br/>
		/// Could be <see langword="null" /> if the constructor couldn't be found.
		/// </summary>
		public static readonly global::System.Reflection.ConstructorInfo? CachedConstructor = typeof(T).GetConstructor(global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic, null, global::System.Type.EmptyTypes, null);

	    public static readonly global::System.Func<T> CompiledDelegate = global::System.Linq.Expressions.Expression.Lambda<Func<T>>(typeof(T).IsValueType
            ? (global::@FastGenericNew.FastNew<T>.CachedConstructor != null
                ? (global::System.Linq.Expressions.Expression)global::System.Linq.Expressions.Expression.New(global::@FastGenericNew.FastNew<T>.CachedConstructor)
                : (global::System.Linq.Expressions.Expression)global::System.Linq.Expressions.Expression.New(typeof(T)))
            : ((global::@FastGenericNew.FastNew<T>.CachedConstructor != null && !typeof(T).IsAbstract)
                ? (global::System.Linq.Expressions.Expression)global::System.Linq.Expressions.Expression.New(global::@FastGenericNew.FastNew<T>.CachedConstructor)
                : (global::System.Linq.Expressions.Expression)global::System.Linq.Expressions.Expression.Call(global::@FastGenericNew.FastNewThrowHelper.GetSmartThrow<T>()))
            , Array.Empty<System.Linq.Expressions.ParameterExpression>()).Compile();
    
        public static readonly bool IsValid = typeof(T).IsValueType || (global::@FastGenericNew.FastNew<T>.CachedConstructor != null && !typeof(T).IsAbstract);
    }
#else
static partial class FastNew<
#if NET5_0_OR_GREATER
[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicParameterlessConstructor | DynamicallyAccessedMemberTypes.NonPublicConstructors)]
#endif
T>
    {
		/// <summary>
		/// The constructor of <typeparamref name="T" /> with given arguments. <br/>
		/// Could be <see langword="null" /> if the constructor couldn't be found.
		/// </summary>
		public static readonly ConstructorInfo? CachedConstructor = typeof(T).GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, null, Type.EmptyTypes, null);

#if NETFRAMEWORK
        [EditorBrowsable(EditorBrowsableState.Never)]
        internal static readonly bool _isValueTypeT = typeof(T).IsValueType;
#endif

	    public static readonly Func<T> CompiledDelegate;
    
        public static readonly bool IsValid = typeof(T).IsValueType || (global::@FastGenericNew.FastNew<T>.CachedConstructor != null && !typeof(T).IsAbstract);
    
        static FastNew()
        {
            var dm = new DynamicMethod("", typeof(T), global::@FastGenericNew._FastNewDynMetClosure.InstanceOnlyArray, restrictedSkipVisibility: true);
            var il = dm.GetILGenerator();
            if (IsValid)
            {
                if (global::@FastGenericNew.FastNew<T>.CachedConstructor != null)
                    il.Emit(OpCodes.Newobj, CachedConstructor!);
                else
                {
                    il.DeclareLocal(typeof(T));
                    //il.Emit(OpCodes.Ldloca_S, (short)0)
                    //il.Emit(OpCodes.Initobj, typeof(T));
                    il.Emit(OpCodes.Ldloc_0);
                }
            }
            else
            {
                il.Emit(OpCodes.Call, global::@FastGenericNew.FastNewThrowHelper.GetSmartThrow<T>());
            }
            il.Emit(OpCodes.Ret);
            CompiledDelegate = (Func<T>)dm.CreateDelegate(typeof(Func<T>), global::@FastGenericNew._FastNewDynMetClosure.Instance);
        }
    }
#endif
	internal static partial class FastNew<
#if NET5_0_OR_GREATER
[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors | DynamicallyAccessedMemberTypes.NonPublicConstructors)]
#endif
T, TArg0>
	{
		/// <summary>
		/// The constructor of <typeparamref name="T" /> with given arguments. <br/>
		/// Could be <see langword="null" /> if the constructor couldn't be found.
		/// </summary>
		public static readonly ConstructorInfo? CachedConstructor = typeof(T).GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, null, new Type[]
		{
			typeof(TArg0),
		}, null);
		public static readonly Func<TArg0, T> CompiledDelegate;

		public static readonly bool IsValid;

		static FastNew()
		{
			IsValid = CachedConstructor != null && !typeof(T).IsAbstract;
#if NETFRAMEWORK
			var p0 = System.Linq.Expressions.Expression.Parameter(typeof(TArg0));
			CompiledDelegate = (System.Linq.Expressions.Expression.Lambda<Func<TArg0, T>>(IsValid
				? (System.Linq.Expressions.Expression)System.Linq.Expressions.Expression.New(CachedConstructor!, p0)
				: (System.Linq.Expressions.Expression)System.Linq.Expressions.Expression.Call(global::@FastGenericNew.FastNewThrowHelper.GetSmartThrow<T>())
			, new System.Linq.Expressions.ParameterExpression[] { p0 })).Compile();
#else
			var dm = new DynamicMethod("", typeof(T), new Type[] { typeof(global::@FastGenericNew._FastNewDynMetClosure), typeof(TArg0) }, restrictedSkipVisibility: true);
			var il = dm.GetILGenerator(10);
			if (IsValid)
			{
				il.Emit(OpCodes.Ldarg_1);
				il.Emit(OpCodes.Newobj, CachedConstructor!);
			}
			else
			{
				il.Emit(OpCodes.Call, global::@FastGenericNew.FastNewThrowHelper.GetSmartThrow<T>());
			}
			il.Emit(OpCodes.Ret);
			CompiledDelegate = (Func<TArg0, T>)dm.CreateDelegate(typeof(Func<TArg0, T>), global::@FastGenericNew._FastNewDynMetClosure.Instance);
#endif
		}
	}
	internal static partial class FastNew<
#if NET5_0_OR_GREATER
[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors | DynamicallyAccessedMemberTypes.NonPublicConstructors)]
#endif
T, TArg0, TArg1>
	{
		/// <summary>
		/// The constructor of <typeparamref name="T" /> with given arguments. <br/>
		/// Could be <see langword="null" /> if the constructor couldn't be found.
		/// </summary>
		public static readonly ConstructorInfo? CachedConstructor = typeof(T).GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, null, new Type[]
		{
			typeof(TArg0),
			typeof(TArg1),
		}, null);
		public static readonly Func<TArg0, TArg1, T> CompiledDelegate;

		public static readonly bool IsValid;

		static FastNew()
		{
			IsValid = CachedConstructor != null && !typeof(T).IsAbstract;
#if NETFRAMEWORK
			var p0 = System.Linq.Expressions.Expression.Parameter(typeof(TArg0));
			var p1 = System.Linq.Expressions.Expression.Parameter(typeof(TArg1));
			CompiledDelegate = (System.Linq.Expressions.Expression.Lambda<Func<TArg0, TArg1, T>>(IsValid
				? (System.Linq.Expressions.Expression)System.Linq.Expressions.Expression.New(CachedConstructor!, p0, p1)
				: (System.Linq.Expressions.Expression)System.Linq.Expressions.Expression.Call(global::@FastGenericNew.FastNewThrowHelper.GetSmartThrow<T>())
			, new System.Linq.Expressions.ParameterExpression[] { p0, p1 })).Compile();
#else
			var dm = new DynamicMethod("", typeof(T), new Type[] { typeof(global::@FastGenericNew._FastNewDynMetClosure), typeof(TArg0), typeof(TArg1) }, restrictedSkipVisibility: true);
			var il = dm.GetILGenerator(11);
			if (IsValid)
			{
				il.Emit(OpCodes.Ldarg_1);
				il.Emit(OpCodes.Ldarg_2);
				il.Emit(OpCodes.Newobj, CachedConstructor!);
			}
			else
			{
				il.Emit(OpCodes.Call, global::@FastGenericNew.FastNewThrowHelper.GetSmartThrow<T>());
			}
			il.Emit(OpCodes.Ret);
			CompiledDelegate = (Func<TArg0, TArg1, T>)dm.CreateDelegate(typeof(Func<TArg0, TArg1, T>), global::@FastGenericNew._FastNewDynMetClosure.Instance);
#endif
		}
	}
	internal static partial class FastNew<
#if NET5_0_OR_GREATER
[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors | DynamicallyAccessedMemberTypes.NonPublicConstructors)]
#endif
T, TArg0, TArg1, TArg2>
	{
		/// <summary>
		/// The constructor of <typeparamref name="T" /> with given arguments. <br/>
		/// Could be <see langword="null" /> if the constructor couldn't be found.
		/// </summary>
		public static readonly ConstructorInfo? CachedConstructor = typeof(T).GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, null, new Type[]
		{
			typeof(TArg0),
			typeof(TArg1),
			typeof(TArg2),
		}, null);
		public static readonly Func<TArg0, TArg1, TArg2, T> CompiledDelegate;

		public static readonly bool IsValid;

		static FastNew()
		{
			IsValid = CachedConstructor != null && !typeof(T).IsAbstract;
#if NETFRAMEWORK
			var p0 = System.Linq.Expressions.Expression.Parameter(typeof(TArg0));
			var p1 = System.Linq.Expressions.Expression.Parameter(typeof(TArg1));
			var p2 = System.Linq.Expressions.Expression.Parameter(typeof(TArg2));
			CompiledDelegate = (System.Linq.Expressions.Expression.Lambda<Func<TArg0, TArg1, TArg2, T>>(IsValid
				? (System.Linq.Expressions.Expression)System.Linq.Expressions.Expression.New(CachedConstructor!, p0, p1, p2)
				: (System.Linq.Expressions.Expression)System.Linq.Expressions.Expression.Call(global::@FastGenericNew.FastNewThrowHelper.GetSmartThrow<T>())
			, new System.Linq.Expressions.ParameterExpression[] { p0, p1, p2 })).Compile();
#else
			var dm = new DynamicMethod("", typeof(T), new Type[] { typeof(global::@FastGenericNew._FastNewDynMetClosure), typeof(TArg0), typeof(TArg1), typeof(TArg2) }, restrictedSkipVisibility: true);
			var il = dm.GetILGenerator(12);
			if (IsValid)
			{
				il.Emit(OpCodes.Ldarg_1);
				il.Emit(OpCodes.Ldarg_2);
				il.Emit(OpCodes.Ldarg_3);
				il.Emit(OpCodes.Newobj, CachedConstructor!);
			}
			else
			{
				il.Emit(OpCodes.Call, global::@FastGenericNew.FastNewThrowHelper.GetSmartThrow<T>());
			}
			il.Emit(OpCodes.Ret);
			CompiledDelegate = (Func<TArg0, TArg1, TArg2, T>)dm.CreateDelegate(typeof(Func<TArg0, TArg1, TArg2, T>), global::@FastGenericNew._FastNewDynMetClosure.Instance);
#endif
		}
	}
	internal static partial class FastNew<
#if NET5_0_OR_GREATER
[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors | DynamicallyAccessedMemberTypes.NonPublicConstructors)]
#endif
T, TArg0, TArg1, TArg2, TArg3>
	{
		/// <summary>
		/// The constructor of <typeparamref name="T" /> with given arguments. <br/>
		/// Could be <see langword="null" /> if the constructor couldn't be found.
		/// </summary>
		public static readonly ConstructorInfo? CachedConstructor = typeof(T).GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, null, new Type[]
		{
			typeof(TArg0),
			typeof(TArg1),
			typeof(TArg2),
			typeof(TArg3),
		}, null);
		public static readonly Func<TArg0, TArg1, TArg2, TArg3, T> CompiledDelegate;

		public static readonly bool IsValid;

		static FastNew()
		{
			IsValid = CachedConstructor != null && !typeof(T).IsAbstract;
#if NETFRAMEWORK
			var p0 = System.Linq.Expressions.Expression.Parameter(typeof(TArg0));
			var p1 = System.Linq.Expressions.Expression.Parameter(typeof(TArg1));
			var p2 = System.Linq.Expressions.Expression.Parameter(typeof(TArg2));
			var p3 = System.Linq.Expressions.Expression.Parameter(typeof(TArg3));
			CompiledDelegate = (System.Linq.Expressions.Expression.Lambda<Func<TArg0, TArg1, TArg2, TArg3, T>>(IsValid
				? (System.Linq.Expressions.Expression)System.Linq.Expressions.Expression.New(CachedConstructor!, p0, p1, p2, p3)
				: (System.Linq.Expressions.Expression)System.Linq.Expressions.Expression.Call(global::@FastGenericNew.FastNewThrowHelper.GetSmartThrow<T>())
			, new System.Linq.Expressions.ParameterExpression[] { p0, p1, p2, p3 })).Compile();
#else
			var dm = new DynamicMethod("", typeof(T), new Type[] { typeof(global::@FastGenericNew._FastNewDynMetClosure), typeof(TArg0), typeof(TArg1), typeof(TArg2), typeof(TArg3) }, restrictedSkipVisibility: true);
			var il = dm.GetILGenerator(13);
			if (IsValid)
			{
				il.Emit(OpCodes.Ldarg_1);
				il.Emit(OpCodes.Ldarg_2);
				il.Emit(OpCodes.Ldarg_3);
				il.Emit(OpCodes.Ldarg_S, (byte)4);
				il.Emit(OpCodes.Newobj, CachedConstructor!);
			}
			else
			{
				il.Emit(OpCodes.Call, global::@FastGenericNew.FastNewThrowHelper.GetSmartThrow<T>());
			}
			il.Emit(OpCodes.Ret);
			CompiledDelegate = (Func<TArg0, TArg1, TArg2, TArg3, T>)dm.CreateDelegate(typeof(Func<TArg0, TArg1, TArg2, TArg3, T>), global::@FastGenericNew._FastNewDynMetClosure.Instance);
#endif
		}
	}
	internal static partial class FastNew<
#if NET5_0_OR_GREATER
[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors | DynamicallyAccessedMemberTypes.NonPublicConstructors)]
#endif
T, TArg0, TArg1, TArg2, TArg3, TArg4>
	{
		/// <summary>
		/// The constructor of <typeparamref name="T" /> with given arguments. <br/>
		/// Could be <see langword="null" /> if the constructor couldn't be found.
		/// </summary>
		public static readonly ConstructorInfo? CachedConstructor = typeof(T).GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, null, new Type[]
		{
			typeof(TArg0),
			typeof(TArg1),
			typeof(TArg2),
			typeof(TArg3),
			typeof(TArg4),
		}, null);
		public static readonly Func<TArg0, TArg1, TArg2, TArg3, TArg4, T> CompiledDelegate;

		public static readonly bool IsValid;

		static FastNew()
		{
			IsValid = CachedConstructor != null && !typeof(T).IsAbstract;
#if NETFRAMEWORK
			var p0 = System.Linq.Expressions.Expression.Parameter(typeof(TArg0));
			var p1 = System.Linq.Expressions.Expression.Parameter(typeof(TArg1));
			var p2 = System.Linq.Expressions.Expression.Parameter(typeof(TArg2));
			var p3 = System.Linq.Expressions.Expression.Parameter(typeof(TArg3));
			var p4 = System.Linq.Expressions.Expression.Parameter(typeof(TArg4));
			CompiledDelegate = (System.Linq.Expressions.Expression.Lambda<Func<TArg0, TArg1, TArg2, TArg3, TArg4, T>>(IsValid
				? (System.Linq.Expressions.Expression)System.Linq.Expressions.Expression.New(CachedConstructor!, p0, p1, p2, p3, p4)
				: (System.Linq.Expressions.Expression)System.Linq.Expressions.Expression.Call(global::@FastGenericNew.FastNewThrowHelper.GetSmartThrow<T>())
			, new System.Linq.Expressions.ParameterExpression[] { p0, p1, p2, p3, p4 })).Compile();
#else
			var dm = new DynamicMethod("", typeof(T), new Type[] { typeof(global::@FastGenericNew._FastNewDynMetClosure), typeof(TArg0), typeof(TArg1), typeof(TArg2), typeof(TArg3), typeof(TArg4) }, restrictedSkipVisibility: true);
			var il = dm.GetILGenerator(14);
			if (IsValid)
			{
				il.Emit(OpCodes.Ldarg_1);
				il.Emit(OpCodes.Ldarg_2);
				il.Emit(OpCodes.Ldarg_3);
				il.Emit(OpCodes.Ldarg_S, (byte)4);
				il.Emit(OpCodes.Ldarg_S, (byte)5);
				il.Emit(OpCodes.Newobj, CachedConstructor!);
			}
			else
			{
				il.Emit(OpCodes.Call, global::@FastGenericNew.FastNewThrowHelper.GetSmartThrow<T>());
			}
			il.Emit(OpCodes.Ret);
			CompiledDelegate = (Func<TArg0, TArg1, TArg2, TArg3, TArg4, T>)dm.CreateDelegate(typeof(Func<TArg0, TArg1, TArg2, TArg3, TArg4, T>), global::@FastGenericNew._FastNewDynMetClosure.Instance);
#endif
		}
	}
	internal static partial class FastNew<
#if NET5_0_OR_GREATER
[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors | DynamicallyAccessedMemberTypes.NonPublicConstructors)]
#endif
T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5>
	{
		/// <summary>
		/// The constructor of <typeparamref name="T" /> with given arguments. <br/>
		/// Could be <see langword="null" /> if the constructor couldn't be found.
		/// </summary>
		public static readonly ConstructorInfo? CachedConstructor = typeof(T).GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, null, new Type[]
		{
			typeof(TArg0),
			typeof(TArg1),
			typeof(TArg2),
			typeof(TArg3),
			typeof(TArg4),
			typeof(TArg5),
		}, null);
		public static readonly Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, T> CompiledDelegate;

		public static readonly bool IsValid;

		static FastNew()
		{
			IsValid = CachedConstructor != null && !typeof(T).IsAbstract;
#if NETFRAMEWORK
			var p0 = System.Linq.Expressions.Expression.Parameter(typeof(TArg0));
			var p1 = System.Linq.Expressions.Expression.Parameter(typeof(TArg1));
			var p2 = System.Linq.Expressions.Expression.Parameter(typeof(TArg2));
			var p3 = System.Linq.Expressions.Expression.Parameter(typeof(TArg3));
			var p4 = System.Linq.Expressions.Expression.Parameter(typeof(TArg4));
			var p5 = System.Linq.Expressions.Expression.Parameter(typeof(TArg5));
			CompiledDelegate = (System.Linq.Expressions.Expression.Lambda<Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, T>>(IsValid
				? (System.Linq.Expressions.Expression)System.Linq.Expressions.Expression.New(CachedConstructor!, p0, p1, p2, p3, p4, p5)
				: (System.Linq.Expressions.Expression)System.Linq.Expressions.Expression.Call(global::@FastGenericNew.FastNewThrowHelper.GetSmartThrow<T>())
			, new System.Linq.Expressions.ParameterExpression[] { p0, p1, p2, p3, p4, p5 })).Compile();
#else
			var dm = new DynamicMethod("", typeof(T), new Type[] { typeof(global::@FastGenericNew._FastNewDynMetClosure), typeof(TArg0), typeof(TArg1), typeof(TArg2), typeof(TArg3), typeof(TArg4), typeof(TArg5) }, restrictedSkipVisibility: true);
			var il = dm.GetILGenerator(15);
			if (IsValid)
			{
				il.Emit(OpCodes.Ldarg_1);
				il.Emit(OpCodes.Ldarg_2);
				il.Emit(OpCodes.Ldarg_3);
				il.Emit(OpCodes.Ldarg_S, (byte)4);
				il.Emit(OpCodes.Ldarg_S, (byte)5);
				il.Emit(OpCodes.Ldarg_S, (byte)6);
				il.Emit(OpCodes.Newobj, CachedConstructor!);
			}
			else
			{
				il.Emit(OpCodes.Call, global::@FastGenericNew.FastNewThrowHelper.GetSmartThrow<T>());
			}
			il.Emit(OpCodes.Ret);
			CompiledDelegate = (Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, T>)dm.CreateDelegate(typeof(Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, T>), global::@FastGenericNew._FastNewDynMetClosure.Instance);
#endif
		}
	}
	internal static partial class FastNew<
#if NET5_0_OR_GREATER
[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors | DynamicallyAccessedMemberTypes.NonPublicConstructors)]
#endif
T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6>
	{
		/// <summary>
		/// The constructor of <typeparamref name="T" /> with given arguments. <br/>
		/// Could be <see langword="null" /> if the constructor couldn't be found.
		/// </summary>
		public static readonly ConstructorInfo? CachedConstructor = typeof(T).GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, null, new Type[]
		{
			typeof(TArg0),
			typeof(TArg1),
			typeof(TArg2),
			typeof(TArg3),
			typeof(TArg4),
			typeof(TArg5),
			typeof(TArg6),
		}, null);
		public static readonly Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, T> CompiledDelegate;

		public static readonly bool IsValid;

		static FastNew()
		{
			IsValid = CachedConstructor != null && !typeof(T).IsAbstract;
#if NETFRAMEWORK
			var p0 = System.Linq.Expressions.Expression.Parameter(typeof(TArg0));
			var p1 = System.Linq.Expressions.Expression.Parameter(typeof(TArg1));
			var p2 = System.Linq.Expressions.Expression.Parameter(typeof(TArg2));
			var p3 = System.Linq.Expressions.Expression.Parameter(typeof(TArg3));
			var p4 = System.Linq.Expressions.Expression.Parameter(typeof(TArg4));
			var p5 = System.Linq.Expressions.Expression.Parameter(typeof(TArg5));
			var p6 = System.Linq.Expressions.Expression.Parameter(typeof(TArg6));
			CompiledDelegate = (System.Linq.Expressions.Expression.Lambda<Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, T>>(IsValid
				? (System.Linq.Expressions.Expression)System.Linq.Expressions.Expression.New(CachedConstructor!, p0, p1, p2, p3, p4, p5, p6)
				: (System.Linq.Expressions.Expression)System.Linq.Expressions.Expression.Call(global::@FastGenericNew.FastNewThrowHelper.GetSmartThrow<T>())
			, new System.Linq.Expressions.ParameterExpression[] { p0, p1, p2, p3, p4, p5, p6 })).Compile();
#else
			var dm = new DynamicMethod("", typeof(T), new Type[] { typeof(global::@FastGenericNew._FastNewDynMetClosure), typeof(TArg0), typeof(TArg1), typeof(TArg2), typeof(TArg3), typeof(TArg4), typeof(TArg5), typeof(TArg6) }, restrictedSkipVisibility: true);
			var il = dm.GetILGenerator(16);
			if (IsValid)
			{
				il.Emit(OpCodes.Ldarg_1);
				il.Emit(OpCodes.Ldarg_2);
				il.Emit(OpCodes.Ldarg_3);
				il.Emit(OpCodes.Ldarg_S, (byte)4);
				il.Emit(OpCodes.Ldarg_S, (byte)5);
				il.Emit(OpCodes.Ldarg_S, (byte)6);
				il.Emit(OpCodes.Ldarg_S, (byte)7);
				il.Emit(OpCodes.Newobj, CachedConstructor!);
			}
			else
			{
				il.Emit(OpCodes.Call, global::@FastGenericNew.FastNewThrowHelper.GetSmartThrow<T>());
			}
			il.Emit(OpCodes.Ret);
			CompiledDelegate = (Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, T>)dm.CreateDelegate(typeof(Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, T>), global::@FastGenericNew._FastNewDynMetClosure.Instance);
#endif
		}
	}
	internal static partial class FastNew<
#if NET5_0_OR_GREATER
[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors | DynamicallyAccessedMemberTypes.NonPublicConstructors)]
#endif
T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7>
	{
		/// <summary>
		/// The constructor of <typeparamref name="T" /> with given arguments. <br/>
		/// Could be <see langword="null" /> if the constructor couldn't be found.
		/// </summary>
		public static readonly ConstructorInfo? CachedConstructor = typeof(T).GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, null, new Type[]
		{
			typeof(TArg0),
			typeof(TArg1),
			typeof(TArg2),
			typeof(TArg3),
			typeof(TArg4),
			typeof(TArg5),
			typeof(TArg6),
			typeof(TArg7),
		}, null);
		public static readonly Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, T> CompiledDelegate;

		public static readonly bool IsValid;

		static FastNew()
		{
			IsValid = CachedConstructor != null && !typeof(T).IsAbstract;
#if NETFRAMEWORK
			var p0 = System.Linq.Expressions.Expression.Parameter(typeof(TArg0));
			var p1 = System.Linq.Expressions.Expression.Parameter(typeof(TArg1));
			var p2 = System.Linq.Expressions.Expression.Parameter(typeof(TArg2));
			var p3 = System.Linq.Expressions.Expression.Parameter(typeof(TArg3));
			var p4 = System.Linq.Expressions.Expression.Parameter(typeof(TArg4));
			var p5 = System.Linq.Expressions.Expression.Parameter(typeof(TArg5));
			var p6 = System.Linq.Expressions.Expression.Parameter(typeof(TArg6));
			var p7 = System.Linq.Expressions.Expression.Parameter(typeof(TArg7));
			CompiledDelegate = (System.Linq.Expressions.Expression.Lambda<Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, T>>(IsValid
				? (System.Linq.Expressions.Expression)System.Linq.Expressions.Expression.New(CachedConstructor!, p0, p1, p2, p3, p4, p5, p6, p7)
				: (System.Linq.Expressions.Expression)System.Linq.Expressions.Expression.Call(global::@FastGenericNew.FastNewThrowHelper.GetSmartThrow<T>())
			, new System.Linq.Expressions.ParameterExpression[] { p0, p1, p2, p3, p4, p5, p6, p7 })).Compile();
#else
			var dm = new DynamicMethod("", typeof(T), new Type[] { typeof(global::@FastGenericNew._FastNewDynMetClosure), typeof(TArg0), typeof(TArg1), typeof(TArg2), typeof(TArg3), typeof(TArg4), typeof(TArg5), typeof(TArg6), typeof(TArg7) }, restrictedSkipVisibility: true);
			var il = dm.GetILGenerator(17);
			if (IsValid)
			{
				il.Emit(OpCodes.Ldarg_1);
				il.Emit(OpCodes.Ldarg_2);
				il.Emit(OpCodes.Ldarg_3);
				il.Emit(OpCodes.Ldarg_S, (byte)4);
				il.Emit(OpCodes.Ldarg_S, (byte)5);
				il.Emit(OpCodes.Ldarg_S, (byte)6);
				il.Emit(OpCodes.Ldarg_S, (byte)7);
				il.Emit(OpCodes.Ldarg_S, (byte)8);
				il.Emit(OpCodes.Newobj, CachedConstructor!);
			}
			else
			{
				il.Emit(OpCodes.Call, global::@FastGenericNew.FastNewThrowHelper.GetSmartThrow<T>());
			}
			il.Emit(OpCodes.Ret);
			CompiledDelegate = (Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, T>)dm.CreateDelegate(typeof(Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, T>), global::@FastGenericNew._FastNewDynMetClosure.Instance);
#endif
		}
	}
	internal static partial class FastNew<
#if NET5_0_OR_GREATER
[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors | DynamicallyAccessedMemberTypes.NonPublicConstructors)]
#endif
T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8>
	{
		/// <summary>
		/// The constructor of <typeparamref name="T" /> with given arguments. <br/>
		/// Could be <see langword="null" /> if the constructor couldn't be found.
		/// </summary>
		public static readonly ConstructorInfo? CachedConstructor = typeof(T).GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, null, new Type[]
		{
			typeof(TArg0),
			typeof(TArg1),
			typeof(TArg2),
			typeof(TArg3),
			typeof(TArg4),
			typeof(TArg5),
			typeof(TArg6),
			typeof(TArg7),
			typeof(TArg8),
		}, null);
		public static readonly Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, T> CompiledDelegate;

		public static readonly bool IsValid;

		static FastNew()
		{
			IsValid = CachedConstructor != null && !typeof(T).IsAbstract;
#if NETFRAMEWORK
			var p0 = System.Linq.Expressions.Expression.Parameter(typeof(TArg0));
			var p1 = System.Linq.Expressions.Expression.Parameter(typeof(TArg1));
			var p2 = System.Linq.Expressions.Expression.Parameter(typeof(TArg2));
			var p3 = System.Linq.Expressions.Expression.Parameter(typeof(TArg3));
			var p4 = System.Linq.Expressions.Expression.Parameter(typeof(TArg4));
			var p5 = System.Linq.Expressions.Expression.Parameter(typeof(TArg5));
			var p6 = System.Linq.Expressions.Expression.Parameter(typeof(TArg6));
			var p7 = System.Linq.Expressions.Expression.Parameter(typeof(TArg7));
			var p8 = System.Linq.Expressions.Expression.Parameter(typeof(TArg8));
			CompiledDelegate = (System.Linq.Expressions.Expression.Lambda<Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, T>>(IsValid
				? (System.Linq.Expressions.Expression)System.Linq.Expressions.Expression.New(CachedConstructor!, p0, p1, p2, p3, p4, p5, p6, p7, p8)
				: (System.Linq.Expressions.Expression)System.Linq.Expressions.Expression.Call(global::@FastGenericNew.FastNewThrowHelper.GetSmartThrow<T>())
			, new System.Linq.Expressions.ParameterExpression[] { p0, p1, p2, p3, p4, p5, p6, p7, p8 })).Compile();
#else
			var dm = new DynamicMethod("", typeof(T), new Type[] { typeof(global::@FastGenericNew._FastNewDynMetClosure), typeof(TArg0), typeof(TArg1), typeof(TArg2), typeof(TArg3), typeof(TArg4), typeof(TArg5), typeof(TArg6), typeof(TArg7), typeof(TArg8) }, restrictedSkipVisibility: true);
			var il = dm.GetILGenerator(18);
			if (IsValid)
			{
				il.Emit(OpCodes.Ldarg_1);
				il.Emit(OpCodes.Ldarg_2);
				il.Emit(OpCodes.Ldarg_3);
				il.Emit(OpCodes.Ldarg_S, (byte)4);
				il.Emit(OpCodes.Ldarg_S, (byte)5);
				il.Emit(OpCodes.Ldarg_S, (byte)6);
				il.Emit(OpCodes.Ldarg_S, (byte)7);
				il.Emit(OpCodes.Ldarg_S, (byte)8);
				il.Emit(OpCodes.Ldarg_S, (byte)9);
				il.Emit(OpCodes.Newobj, CachedConstructor!);
			}
			else
			{
				il.Emit(OpCodes.Call, global::@FastGenericNew.FastNewThrowHelper.GetSmartThrow<T>());
			}
			il.Emit(OpCodes.Ret);
			CompiledDelegate = (Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, T>)dm.CreateDelegate(typeof(Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, T>), global::@FastGenericNew._FastNewDynMetClosure.Instance);
#endif
		}
	}
	internal static partial class FastNew<
#if NET5_0_OR_GREATER
[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors | DynamicallyAccessedMemberTypes.NonPublicConstructors)]
#endif
T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9>
	{
		/// <summary>
		/// The constructor of <typeparamref name="T" /> with given arguments. <br/>
		/// Could be <see langword="null" /> if the constructor couldn't be found.
		/// </summary>
		public static readonly ConstructorInfo? CachedConstructor = typeof(T).GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, null, new Type[]
		{
			typeof(TArg0),
			typeof(TArg1),
			typeof(TArg2),
			typeof(TArg3),
			typeof(TArg4),
			typeof(TArg5),
			typeof(TArg6),
			typeof(TArg7),
			typeof(TArg8),
			typeof(TArg9),
		}, null);
		public static readonly Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, T> CompiledDelegate;

		public static readonly bool IsValid;

		static FastNew()
		{
			IsValid = CachedConstructor != null && !typeof(T).IsAbstract;
#if NETFRAMEWORK
			var p0 = System.Linq.Expressions.Expression.Parameter(typeof(TArg0));
			var p1 = System.Linq.Expressions.Expression.Parameter(typeof(TArg1));
			var p2 = System.Linq.Expressions.Expression.Parameter(typeof(TArg2));
			var p3 = System.Linq.Expressions.Expression.Parameter(typeof(TArg3));
			var p4 = System.Linq.Expressions.Expression.Parameter(typeof(TArg4));
			var p5 = System.Linq.Expressions.Expression.Parameter(typeof(TArg5));
			var p6 = System.Linq.Expressions.Expression.Parameter(typeof(TArg6));
			var p7 = System.Linq.Expressions.Expression.Parameter(typeof(TArg7));
			var p8 = System.Linq.Expressions.Expression.Parameter(typeof(TArg8));
			var p9 = System.Linq.Expressions.Expression.Parameter(typeof(TArg9));
			CompiledDelegate = (System.Linq.Expressions.Expression.Lambda<Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, T>>(IsValid
				? (System.Linq.Expressions.Expression)System.Linq.Expressions.Expression.New(CachedConstructor!, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9)
				: (System.Linq.Expressions.Expression)System.Linq.Expressions.Expression.Call(global::@FastGenericNew.FastNewThrowHelper.GetSmartThrow<T>())
			, new System.Linq.Expressions.ParameterExpression[] { p0, p1, p2, p3, p4, p5, p6, p7, p8, p9 })).Compile();
#else
			var dm = new DynamicMethod("", typeof(T), new Type[] { typeof(global::@FastGenericNew._FastNewDynMetClosure), typeof(TArg0), typeof(TArg1), typeof(TArg2), typeof(TArg3), typeof(TArg4), typeof(TArg5), typeof(TArg6), typeof(TArg7), typeof(TArg8), typeof(TArg9) }, restrictedSkipVisibility: true);
			var il = dm.GetILGenerator(19);
			if (IsValid)
			{
				il.Emit(OpCodes.Ldarg_1);
				il.Emit(OpCodes.Ldarg_2);
				il.Emit(OpCodes.Ldarg_3);
				il.Emit(OpCodes.Ldarg_S, (byte)4);
				il.Emit(OpCodes.Ldarg_S, (byte)5);
				il.Emit(OpCodes.Ldarg_S, (byte)6);
				il.Emit(OpCodes.Ldarg_S, (byte)7);
				il.Emit(OpCodes.Ldarg_S, (byte)8);
				il.Emit(OpCodes.Ldarg_S, (byte)9);
				il.Emit(OpCodes.Ldarg_S, (byte)10);
				il.Emit(OpCodes.Newobj, CachedConstructor!);
			}
			else
			{
				il.Emit(OpCodes.Call, global::@FastGenericNew.FastNewThrowHelper.GetSmartThrow<T>());
			}
			il.Emit(OpCodes.Ret);
			CompiledDelegate = (Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, T>)dm.CreateDelegate(typeof(Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, T>), global::@FastGenericNew._FastNewDynMetClosure.Instance);
#endif
		}
	}
	internal static partial class FastNew<
#if NET5_0_OR_GREATER
[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors | DynamicallyAccessedMemberTypes.NonPublicConstructors)]
#endif
T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10>
	{
		/// <summary>
		/// The constructor of <typeparamref name="T" /> with given arguments. <br/>
		/// Could be <see langword="null" /> if the constructor couldn't be found.
		/// </summary>
		public static readonly ConstructorInfo? CachedConstructor = typeof(T).GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, null, new Type[]
		{
			typeof(TArg0),
			typeof(TArg1),
			typeof(TArg2),
			typeof(TArg3),
			typeof(TArg4),
			typeof(TArg5),
			typeof(TArg6),
			typeof(TArg7),
			typeof(TArg8),
			typeof(TArg9),
			typeof(TArg10),
		}, null);
		public static readonly Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, T> CompiledDelegate;

		public static readonly bool IsValid;

		static FastNew()
		{
			IsValid = CachedConstructor != null && !typeof(T).IsAbstract;
#if NETFRAMEWORK
			var p0 = System.Linq.Expressions.Expression.Parameter(typeof(TArg0));
			var p1 = System.Linq.Expressions.Expression.Parameter(typeof(TArg1));
			var p2 = System.Linq.Expressions.Expression.Parameter(typeof(TArg2));
			var p3 = System.Linq.Expressions.Expression.Parameter(typeof(TArg3));
			var p4 = System.Linq.Expressions.Expression.Parameter(typeof(TArg4));
			var p5 = System.Linq.Expressions.Expression.Parameter(typeof(TArg5));
			var p6 = System.Linq.Expressions.Expression.Parameter(typeof(TArg6));
			var p7 = System.Linq.Expressions.Expression.Parameter(typeof(TArg7));
			var p8 = System.Linq.Expressions.Expression.Parameter(typeof(TArg8));
			var p9 = System.Linq.Expressions.Expression.Parameter(typeof(TArg9));
			var p10 = System.Linq.Expressions.Expression.Parameter(typeof(TArg10));
			CompiledDelegate = (System.Linq.Expressions.Expression.Lambda<Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, T>>(IsValid
				? (System.Linq.Expressions.Expression)System.Linq.Expressions.Expression.New(CachedConstructor!, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10)
				: (System.Linq.Expressions.Expression)System.Linq.Expressions.Expression.Call(global::@FastGenericNew.FastNewThrowHelper.GetSmartThrow<T>())
			, new System.Linq.Expressions.ParameterExpression[] { p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10 })).Compile();
#else
			var dm = new DynamicMethod("", typeof(T), new Type[] { typeof(global::@FastGenericNew._FastNewDynMetClosure), typeof(TArg0), typeof(TArg1), typeof(TArg2), typeof(TArg3), typeof(TArg4), typeof(TArg5), typeof(TArg6), typeof(TArg7), typeof(TArg8), typeof(TArg9), typeof(TArg10) }, restrictedSkipVisibility: true);
			var il = dm.GetILGenerator(20);
			if (IsValid)
			{
				il.Emit(OpCodes.Ldarg_1);
				il.Emit(OpCodes.Ldarg_2);
				il.Emit(OpCodes.Ldarg_3);
				il.Emit(OpCodes.Ldarg_S, (byte)4);
				il.Emit(OpCodes.Ldarg_S, (byte)5);
				il.Emit(OpCodes.Ldarg_S, (byte)6);
				il.Emit(OpCodes.Ldarg_S, (byte)7);
				il.Emit(OpCodes.Ldarg_S, (byte)8);
				il.Emit(OpCodes.Ldarg_S, (byte)9);
				il.Emit(OpCodes.Ldarg_S, (byte)10);
				il.Emit(OpCodes.Ldarg_S, (byte)11);
				il.Emit(OpCodes.Newobj, CachedConstructor!);
			}
			else
			{
				il.Emit(OpCodes.Call, global::@FastGenericNew.FastNewThrowHelper.GetSmartThrow<T>());
			}
			il.Emit(OpCodes.Ret);
			CompiledDelegate = (Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, T>)dm.CreateDelegate(typeof(Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, T>), global::@FastGenericNew._FastNewDynMetClosure.Instance);
#endif
		}
	}
	internal static partial class FastNew<
#if NET5_0_OR_GREATER
[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors | DynamicallyAccessedMemberTypes.NonPublicConstructors)]
#endif
T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11>
	{
		/// <summary>
		/// The constructor of <typeparamref name="T" /> with given arguments. <br/>
		/// Could be <see langword="null" /> if the constructor couldn't be found.
		/// </summary>
		public static readonly ConstructorInfo? CachedConstructor = typeof(T).GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, null, new Type[]
		{
			typeof(TArg0),
			typeof(TArg1),
			typeof(TArg2),
			typeof(TArg3),
			typeof(TArg4),
			typeof(TArg5),
			typeof(TArg6),
			typeof(TArg7),
			typeof(TArg8),
			typeof(TArg9),
			typeof(TArg10),
			typeof(TArg11),
		}, null);
		public static readonly Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, T> CompiledDelegate;

		public static readonly bool IsValid;

		static FastNew()
		{
			IsValid = CachedConstructor != null && !typeof(T).IsAbstract;
#if NETFRAMEWORK
			var p0 = System.Linq.Expressions.Expression.Parameter(typeof(TArg0));
			var p1 = System.Linq.Expressions.Expression.Parameter(typeof(TArg1));
			var p2 = System.Linq.Expressions.Expression.Parameter(typeof(TArg2));
			var p3 = System.Linq.Expressions.Expression.Parameter(typeof(TArg3));
			var p4 = System.Linq.Expressions.Expression.Parameter(typeof(TArg4));
			var p5 = System.Linq.Expressions.Expression.Parameter(typeof(TArg5));
			var p6 = System.Linq.Expressions.Expression.Parameter(typeof(TArg6));
			var p7 = System.Linq.Expressions.Expression.Parameter(typeof(TArg7));
			var p8 = System.Linq.Expressions.Expression.Parameter(typeof(TArg8));
			var p9 = System.Linq.Expressions.Expression.Parameter(typeof(TArg9));
			var p10 = System.Linq.Expressions.Expression.Parameter(typeof(TArg10));
			var p11 = System.Linq.Expressions.Expression.Parameter(typeof(TArg11));
			CompiledDelegate = (System.Linq.Expressions.Expression.Lambda<Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, T>>(IsValid
				? (System.Linq.Expressions.Expression)System.Linq.Expressions.Expression.New(CachedConstructor!, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11)
				: (System.Linq.Expressions.Expression)System.Linq.Expressions.Expression.Call(global::@FastGenericNew.FastNewThrowHelper.GetSmartThrow<T>())
			, new System.Linq.Expressions.ParameterExpression[] { p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11 })).Compile();
#else
			var dm = new DynamicMethod("", typeof(T), new Type[] { typeof(global::@FastGenericNew._FastNewDynMetClosure), typeof(TArg0), typeof(TArg1), typeof(TArg2), typeof(TArg3), typeof(TArg4), typeof(TArg5), typeof(TArg6), typeof(TArg7), typeof(TArg8), typeof(TArg9), typeof(TArg10), typeof(TArg11) }, restrictedSkipVisibility: true);
			var il = dm.GetILGenerator(21);
			if (IsValid)
			{
				il.Emit(OpCodes.Ldarg_1);
				il.Emit(OpCodes.Ldarg_2);
				il.Emit(OpCodes.Ldarg_3);
				il.Emit(OpCodes.Ldarg_S, (byte)4);
				il.Emit(OpCodes.Ldarg_S, (byte)5);
				il.Emit(OpCodes.Ldarg_S, (byte)6);
				il.Emit(OpCodes.Ldarg_S, (byte)7);
				il.Emit(OpCodes.Ldarg_S, (byte)8);
				il.Emit(OpCodes.Ldarg_S, (byte)9);
				il.Emit(OpCodes.Ldarg_S, (byte)10);
				il.Emit(OpCodes.Ldarg_S, (byte)11);
				il.Emit(OpCodes.Ldarg_S, (byte)12);
				il.Emit(OpCodes.Newobj, CachedConstructor!);
			}
			else
			{
				il.Emit(OpCodes.Call, global::@FastGenericNew.FastNewThrowHelper.GetSmartThrow<T>());
			}
			il.Emit(OpCodes.Ret);
			CompiledDelegate = (Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, T>)dm.CreateDelegate(typeof(Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, T>), global::@FastGenericNew._FastNewDynMetClosure.Instance);
#endif
		}
	}
	internal static partial class FastNew<
#if NET5_0_OR_GREATER
[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors | DynamicallyAccessedMemberTypes.NonPublicConstructors)]
#endif
T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12>
	{
		/// <summary>
		/// The constructor of <typeparamref name="T" /> with given arguments. <br/>
		/// Could be <see langword="null" /> if the constructor couldn't be found.
		/// </summary>
		public static readonly ConstructorInfo? CachedConstructor = typeof(T).GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, null, new Type[]
		{
			typeof(TArg0),
			typeof(TArg1),
			typeof(TArg2),
			typeof(TArg3),
			typeof(TArg4),
			typeof(TArg5),
			typeof(TArg6),
			typeof(TArg7),
			typeof(TArg8),
			typeof(TArg9),
			typeof(TArg10),
			typeof(TArg11),
			typeof(TArg12),
		}, null);
		public static readonly Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, T> CompiledDelegate;

		public static readonly bool IsValid;

		static FastNew()
		{
			IsValid = CachedConstructor != null && !typeof(T).IsAbstract;
#if NETFRAMEWORK
			var p0 = System.Linq.Expressions.Expression.Parameter(typeof(TArg0));
			var p1 = System.Linq.Expressions.Expression.Parameter(typeof(TArg1));
			var p2 = System.Linq.Expressions.Expression.Parameter(typeof(TArg2));
			var p3 = System.Linq.Expressions.Expression.Parameter(typeof(TArg3));
			var p4 = System.Linq.Expressions.Expression.Parameter(typeof(TArg4));
			var p5 = System.Linq.Expressions.Expression.Parameter(typeof(TArg5));
			var p6 = System.Linq.Expressions.Expression.Parameter(typeof(TArg6));
			var p7 = System.Linq.Expressions.Expression.Parameter(typeof(TArg7));
			var p8 = System.Linq.Expressions.Expression.Parameter(typeof(TArg8));
			var p9 = System.Linq.Expressions.Expression.Parameter(typeof(TArg9));
			var p10 = System.Linq.Expressions.Expression.Parameter(typeof(TArg10));
			var p11 = System.Linq.Expressions.Expression.Parameter(typeof(TArg11));
			var p12 = System.Linq.Expressions.Expression.Parameter(typeof(TArg12));
			CompiledDelegate = (System.Linq.Expressions.Expression.Lambda<Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, T>>(IsValid
				? (System.Linq.Expressions.Expression)System.Linq.Expressions.Expression.New(CachedConstructor!, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12)
				: (System.Linq.Expressions.Expression)System.Linq.Expressions.Expression.Call(global::@FastGenericNew.FastNewThrowHelper.GetSmartThrow<T>())
			, new System.Linq.Expressions.ParameterExpression[] { p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12 })).Compile();
#else
			var dm = new DynamicMethod("", typeof(T), new Type[] { typeof(global::@FastGenericNew._FastNewDynMetClosure), typeof(TArg0), typeof(TArg1), typeof(TArg2), typeof(TArg3), typeof(TArg4), typeof(TArg5), typeof(TArg6), typeof(TArg7), typeof(TArg8), typeof(TArg9), typeof(TArg10), typeof(TArg11), typeof(TArg12) }, restrictedSkipVisibility: true);
			var il = dm.GetILGenerator(22);
			if (IsValid)
			{
				il.Emit(OpCodes.Ldarg_1);
				il.Emit(OpCodes.Ldarg_2);
				il.Emit(OpCodes.Ldarg_3);
				il.Emit(OpCodes.Ldarg_S, (byte)4);
				il.Emit(OpCodes.Ldarg_S, (byte)5);
				il.Emit(OpCodes.Ldarg_S, (byte)6);
				il.Emit(OpCodes.Ldarg_S, (byte)7);
				il.Emit(OpCodes.Ldarg_S, (byte)8);
				il.Emit(OpCodes.Ldarg_S, (byte)9);
				il.Emit(OpCodes.Ldarg_S, (byte)10);
				il.Emit(OpCodes.Ldarg_S, (byte)11);
				il.Emit(OpCodes.Ldarg_S, (byte)12);
				il.Emit(OpCodes.Ldarg_S, (byte)13);
				il.Emit(OpCodes.Newobj, CachedConstructor!);
			}
			else
			{
				il.Emit(OpCodes.Call, global::@FastGenericNew.FastNewThrowHelper.GetSmartThrow<T>());
			}
			il.Emit(OpCodes.Ret);
			CompiledDelegate = (Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, T>)dm.CreateDelegate(typeof(Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, T>), global::@FastGenericNew._FastNewDynMetClosure.Instance);
#endif
		}
	}
	internal static partial class FastNew<
#if NET5_0_OR_GREATER
[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors | DynamicallyAccessedMemberTypes.NonPublicConstructors)]
#endif
T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13>
	{
		/// <summary>
		/// The constructor of <typeparamref name="T" /> with given arguments. <br/>
		/// Could be <see langword="null" /> if the constructor couldn't be found.
		/// </summary>
		public static readonly ConstructorInfo? CachedConstructor = typeof(T).GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, null, new Type[]
		{
			typeof(TArg0),
			typeof(TArg1),
			typeof(TArg2),
			typeof(TArg3),
			typeof(TArg4),
			typeof(TArg5),
			typeof(TArg6),
			typeof(TArg7),
			typeof(TArg8),
			typeof(TArg9),
			typeof(TArg10),
			typeof(TArg11),
			typeof(TArg12),
			typeof(TArg13),
		}, null);
		public static readonly Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, T> CompiledDelegate;

		public static readonly bool IsValid;

		static FastNew()
		{
			IsValid = CachedConstructor != null && !typeof(T).IsAbstract;
#if NETFRAMEWORK
			var p0 = System.Linq.Expressions.Expression.Parameter(typeof(TArg0));
			var p1 = System.Linq.Expressions.Expression.Parameter(typeof(TArg1));
			var p2 = System.Linq.Expressions.Expression.Parameter(typeof(TArg2));
			var p3 = System.Linq.Expressions.Expression.Parameter(typeof(TArg3));
			var p4 = System.Linq.Expressions.Expression.Parameter(typeof(TArg4));
			var p5 = System.Linq.Expressions.Expression.Parameter(typeof(TArg5));
			var p6 = System.Linq.Expressions.Expression.Parameter(typeof(TArg6));
			var p7 = System.Linq.Expressions.Expression.Parameter(typeof(TArg7));
			var p8 = System.Linq.Expressions.Expression.Parameter(typeof(TArg8));
			var p9 = System.Linq.Expressions.Expression.Parameter(typeof(TArg9));
			var p10 = System.Linq.Expressions.Expression.Parameter(typeof(TArg10));
			var p11 = System.Linq.Expressions.Expression.Parameter(typeof(TArg11));
			var p12 = System.Linq.Expressions.Expression.Parameter(typeof(TArg12));
			var p13 = System.Linq.Expressions.Expression.Parameter(typeof(TArg13));
			CompiledDelegate = (System.Linq.Expressions.Expression.Lambda<Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, T>>(IsValid
				? (System.Linq.Expressions.Expression)System.Linq.Expressions.Expression.New(CachedConstructor!, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13)
				: (System.Linq.Expressions.Expression)System.Linq.Expressions.Expression.Call(global::@FastGenericNew.FastNewThrowHelper.GetSmartThrow<T>())
			, new System.Linq.Expressions.ParameterExpression[] { p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13 })).Compile();
#else
			var dm = new DynamicMethod("", typeof(T), new Type[] { typeof(global::@FastGenericNew._FastNewDynMetClosure), typeof(TArg0), typeof(TArg1), typeof(TArg2), typeof(TArg3), typeof(TArg4), typeof(TArg5), typeof(TArg6), typeof(TArg7), typeof(TArg8), typeof(TArg9), typeof(TArg10), typeof(TArg11), typeof(TArg12), typeof(TArg13) }, restrictedSkipVisibility: true);
			var il = dm.GetILGenerator(23);
			if (IsValid)
			{
				il.Emit(OpCodes.Ldarg_1);
				il.Emit(OpCodes.Ldarg_2);
				il.Emit(OpCodes.Ldarg_3);
				il.Emit(OpCodes.Ldarg_S, (byte)4);
				il.Emit(OpCodes.Ldarg_S, (byte)5);
				il.Emit(OpCodes.Ldarg_S, (byte)6);
				il.Emit(OpCodes.Ldarg_S, (byte)7);
				il.Emit(OpCodes.Ldarg_S, (byte)8);
				il.Emit(OpCodes.Ldarg_S, (byte)9);
				il.Emit(OpCodes.Ldarg_S, (byte)10);
				il.Emit(OpCodes.Ldarg_S, (byte)11);
				il.Emit(OpCodes.Ldarg_S, (byte)12);
				il.Emit(OpCodes.Ldarg_S, (byte)13);
				il.Emit(OpCodes.Ldarg_S, (byte)14);
				il.Emit(OpCodes.Newobj, CachedConstructor!);
			}
			else
			{
				il.Emit(OpCodes.Call, global::@FastGenericNew.FastNewThrowHelper.GetSmartThrow<T>());
			}
			il.Emit(OpCodes.Ret);
			CompiledDelegate = (Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, T>)dm.CreateDelegate(typeof(Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, T>), global::@FastGenericNew._FastNewDynMetClosure.Instance);
#endif
		}
	}
	internal static partial class FastNew<
#if NET5_0_OR_GREATER
[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors | DynamicallyAccessedMemberTypes.NonPublicConstructors)]
#endif
T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TArg14>
	{
		/// <summary>
		/// The constructor of <typeparamref name="T" /> with given arguments. <br/>
		/// Could be <see langword="null" /> if the constructor couldn't be found.
		/// </summary>
		public static readonly ConstructorInfo? CachedConstructor = typeof(T).GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, null, new Type[]
		{
			typeof(TArg0),
			typeof(TArg1),
			typeof(TArg2),
			typeof(TArg3),
			typeof(TArg4),
			typeof(TArg5),
			typeof(TArg6),
			typeof(TArg7),
			typeof(TArg8),
			typeof(TArg9),
			typeof(TArg10),
			typeof(TArg11),
			typeof(TArg12),
			typeof(TArg13),
			typeof(TArg14),
		}, null);
		public static readonly Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TArg14, T> CompiledDelegate;

		public static readonly bool IsValid;

		static FastNew()
		{
			IsValid = CachedConstructor != null && !typeof(T).IsAbstract;
#if NETFRAMEWORK
			var p0 = System.Linq.Expressions.Expression.Parameter(typeof(TArg0));
			var p1 = System.Linq.Expressions.Expression.Parameter(typeof(TArg1));
			var p2 = System.Linq.Expressions.Expression.Parameter(typeof(TArg2));
			var p3 = System.Linq.Expressions.Expression.Parameter(typeof(TArg3));
			var p4 = System.Linq.Expressions.Expression.Parameter(typeof(TArg4));
			var p5 = System.Linq.Expressions.Expression.Parameter(typeof(TArg5));
			var p6 = System.Linq.Expressions.Expression.Parameter(typeof(TArg6));
			var p7 = System.Linq.Expressions.Expression.Parameter(typeof(TArg7));
			var p8 = System.Linq.Expressions.Expression.Parameter(typeof(TArg8));
			var p9 = System.Linq.Expressions.Expression.Parameter(typeof(TArg9));
			var p10 = System.Linq.Expressions.Expression.Parameter(typeof(TArg10));
			var p11 = System.Linq.Expressions.Expression.Parameter(typeof(TArg11));
			var p12 = System.Linq.Expressions.Expression.Parameter(typeof(TArg12));
			var p13 = System.Linq.Expressions.Expression.Parameter(typeof(TArg13));
			var p14 = System.Linq.Expressions.Expression.Parameter(typeof(TArg14));
			CompiledDelegate = (System.Linq.Expressions.Expression.Lambda<Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TArg14, T>>(IsValid
				? (System.Linq.Expressions.Expression)System.Linq.Expressions.Expression.New(CachedConstructor!, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14)
				: (System.Linq.Expressions.Expression)System.Linq.Expressions.Expression.Call(global::@FastGenericNew.FastNewThrowHelper.GetSmartThrow<T>())
			, new System.Linq.Expressions.ParameterExpression[] { p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14 })).Compile();
#else
			var dm = new DynamicMethod("", typeof(T), new Type[] { typeof(global::@FastGenericNew._FastNewDynMetClosure), typeof(TArg0), typeof(TArg1), typeof(TArg2), typeof(TArg3), typeof(TArg4), typeof(TArg5), typeof(TArg6), typeof(TArg7), typeof(TArg8), typeof(TArg9), typeof(TArg10), typeof(TArg11), typeof(TArg12), typeof(TArg13), typeof(TArg14) }, restrictedSkipVisibility: true);
			var il = dm.GetILGenerator(24);
			if (IsValid)
			{
				il.Emit(OpCodes.Ldarg_1);
				il.Emit(OpCodes.Ldarg_2);
				il.Emit(OpCodes.Ldarg_3);
				il.Emit(OpCodes.Ldarg_S, (byte)4);
				il.Emit(OpCodes.Ldarg_S, (byte)5);
				il.Emit(OpCodes.Ldarg_S, (byte)6);
				il.Emit(OpCodes.Ldarg_S, (byte)7);
				il.Emit(OpCodes.Ldarg_S, (byte)8);
				il.Emit(OpCodes.Ldarg_S, (byte)9);
				il.Emit(OpCodes.Ldarg_S, (byte)10);
				il.Emit(OpCodes.Ldarg_S, (byte)11);
				il.Emit(OpCodes.Ldarg_S, (byte)12);
				il.Emit(OpCodes.Ldarg_S, (byte)13);
				il.Emit(OpCodes.Ldarg_S, (byte)14);
				il.Emit(OpCodes.Ldarg_S, (byte)15);
				il.Emit(OpCodes.Newobj, CachedConstructor!);
			}
			else
			{
				il.Emit(OpCodes.Call, global::@FastGenericNew.FastNewThrowHelper.GetSmartThrow<T>());
			}
			il.Emit(OpCodes.Ret);
			CompiledDelegate = (Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TArg14, T>)dm.CreateDelegate(typeof(Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TArg14, T>), global::@FastGenericNew._FastNewDynMetClosure.Instance);
#endif
		}
	}
	internal static partial class FastNew<
#if NET5_0_OR_GREATER
[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors | DynamicallyAccessedMemberTypes.NonPublicConstructors)]
#endif
T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TArg14, TArg15>
	{
		/// <summary>
		/// The constructor of <typeparamref name="T" /> with given arguments. <br/>
		/// Could be <see langword="null" /> if the constructor couldn't be found.
		/// </summary>
		public static readonly ConstructorInfo? CachedConstructor = typeof(T).GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, null, new Type[]
		{
			typeof(TArg0),
			typeof(TArg1),
			typeof(TArg2),
			typeof(TArg3),
			typeof(TArg4),
			typeof(TArg5),
			typeof(TArg6),
			typeof(TArg7),
			typeof(TArg8),
			typeof(TArg9),
			typeof(TArg10),
			typeof(TArg11),
			typeof(TArg12),
			typeof(TArg13),
			typeof(TArg14),
			typeof(TArg15),
		}, null);
		public static readonly Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TArg14, TArg15, T> CompiledDelegate;

		public static readonly bool IsValid;

		static FastNew()
		{
			IsValid = CachedConstructor != null && !typeof(T).IsAbstract;
#if NETFRAMEWORK
			var p0 = System.Linq.Expressions.Expression.Parameter(typeof(TArg0));
			var p1 = System.Linq.Expressions.Expression.Parameter(typeof(TArg1));
			var p2 = System.Linq.Expressions.Expression.Parameter(typeof(TArg2));
			var p3 = System.Linq.Expressions.Expression.Parameter(typeof(TArg3));
			var p4 = System.Linq.Expressions.Expression.Parameter(typeof(TArg4));
			var p5 = System.Linq.Expressions.Expression.Parameter(typeof(TArg5));
			var p6 = System.Linq.Expressions.Expression.Parameter(typeof(TArg6));
			var p7 = System.Linq.Expressions.Expression.Parameter(typeof(TArg7));
			var p8 = System.Linq.Expressions.Expression.Parameter(typeof(TArg8));
			var p9 = System.Linq.Expressions.Expression.Parameter(typeof(TArg9));
			var p10 = System.Linq.Expressions.Expression.Parameter(typeof(TArg10));
			var p11 = System.Linq.Expressions.Expression.Parameter(typeof(TArg11));
			var p12 = System.Linq.Expressions.Expression.Parameter(typeof(TArg12));
			var p13 = System.Linq.Expressions.Expression.Parameter(typeof(TArg13));
			var p14 = System.Linq.Expressions.Expression.Parameter(typeof(TArg14));
			var p15 = System.Linq.Expressions.Expression.Parameter(typeof(TArg15));
			CompiledDelegate = (System.Linq.Expressions.Expression.Lambda<Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TArg14, TArg15, T>>(IsValid
				? (System.Linq.Expressions.Expression)System.Linq.Expressions.Expression.New(CachedConstructor!, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15)
				: (System.Linq.Expressions.Expression)System.Linq.Expressions.Expression.Call(global::@FastGenericNew.FastNewThrowHelper.GetSmartThrow<T>())
			, new System.Linq.Expressions.ParameterExpression[] { p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15 })).Compile();
#else
			var dm = new DynamicMethod("", typeof(T), new Type[] { typeof(global::@FastGenericNew._FastNewDynMetClosure), typeof(TArg0), typeof(TArg1), typeof(TArg2), typeof(TArg3), typeof(TArg4), typeof(TArg5), typeof(TArg6), typeof(TArg7), typeof(TArg8), typeof(TArg9), typeof(TArg10), typeof(TArg11), typeof(TArg12), typeof(TArg13), typeof(TArg14), typeof(TArg15) }, restrictedSkipVisibility: true);
			var il = dm.GetILGenerator(25);
			if (IsValid)
			{
				il.Emit(OpCodes.Ldarg_1);
				il.Emit(OpCodes.Ldarg_2);
				il.Emit(OpCodes.Ldarg_3);
				il.Emit(OpCodes.Ldarg_S, (byte)4);
				il.Emit(OpCodes.Ldarg_S, (byte)5);
				il.Emit(OpCodes.Ldarg_S, (byte)6);
				il.Emit(OpCodes.Ldarg_S, (byte)7);
				il.Emit(OpCodes.Ldarg_S, (byte)8);
				il.Emit(OpCodes.Ldarg_S, (byte)9);
				il.Emit(OpCodes.Ldarg_S, (byte)10);
				il.Emit(OpCodes.Ldarg_S, (byte)11);
				il.Emit(OpCodes.Ldarg_S, (byte)12);
				il.Emit(OpCodes.Ldarg_S, (byte)13);
				il.Emit(OpCodes.Ldarg_S, (byte)14);
				il.Emit(OpCodes.Ldarg_S, (byte)15);
				il.Emit(OpCodes.Ldarg_S, (byte)16);
				il.Emit(OpCodes.Newobj, CachedConstructor!);
			}
			else
			{
				il.Emit(OpCodes.Call, global::@FastGenericNew.FastNewThrowHelper.GetSmartThrow<T>());
			}
			il.Emit(OpCodes.Ret);
			CompiledDelegate = (Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TArg14, TArg15, T>)dm.CreateDelegate(typeof(Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TArg14, TArg15, T>), global::@FastGenericNew._FastNewDynMetClosure.Instance);
#endif
		}
	}
	internal static partial class FastNew<
#if NET5_0_OR_GREATER
[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors | DynamicallyAccessedMemberTypes.NonPublicConstructors)]
#endif
T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TArg14, TArg15, TArg16>
	{
		/// <summary>
		/// The constructor of <typeparamref name="T" /> with given arguments. <br/>
		/// Could be <see langword="null" /> if the constructor couldn't be found.
		/// </summary>
		public static readonly ConstructorInfo? CachedConstructor = typeof(T).GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, null, new Type[]
		{
			typeof(TArg0),
			typeof(TArg1),
			typeof(TArg2),
			typeof(TArg3),
			typeof(TArg4),
			typeof(TArg5),
			typeof(TArg6),
			typeof(TArg7),
			typeof(TArg8),
			typeof(TArg9),
			typeof(TArg10),
			typeof(TArg11),
			typeof(TArg12),
			typeof(TArg13),
			typeof(TArg14),
			typeof(TArg15),
			typeof(TArg16),
		}, null);
		public static readonly global::@FastGenericNew.FastNew.FastNewDelegate<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TArg14, TArg15, TArg16> CompiledDelegate;

		public static readonly bool IsValid;

		static FastNew()
		{
			IsValid = CachedConstructor != null && !typeof(T).IsAbstract;
#if NETFRAMEWORK
			var p0 = System.Linq.Expressions.Expression.Parameter(typeof(TArg0));
			var p1 = System.Linq.Expressions.Expression.Parameter(typeof(TArg1));
			var p2 = System.Linq.Expressions.Expression.Parameter(typeof(TArg2));
			var p3 = System.Linq.Expressions.Expression.Parameter(typeof(TArg3));
			var p4 = System.Linq.Expressions.Expression.Parameter(typeof(TArg4));
			var p5 = System.Linq.Expressions.Expression.Parameter(typeof(TArg5));
			var p6 = System.Linq.Expressions.Expression.Parameter(typeof(TArg6));
			var p7 = System.Linq.Expressions.Expression.Parameter(typeof(TArg7));
			var p8 = System.Linq.Expressions.Expression.Parameter(typeof(TArg8));
			var p9 = System.Linq.Expressions.Expression.Parameter(typeof(TArg9));
			var p10 = System.Linq.Expressions.Expression.Parameter(typeof(TArg10));
			var p11 = System.Linq.Expressions.Expression.Parameter(typeof(TArg11));
			var p12 = System.Linq.Expressions.Expression.Parameter(typeof(TArg12));
			var p13 = System.Linq.Expressions.Expression.Parameter(typeof(TArg13));
			var p14 = System.Linq.Expressions.Expression.Parameter(typeof(TArg14));
			var p15 = System.Linq.Expressions.Expression.Parameter(typeof(TArg15));
			var p16 = System.Linq.Expressions.Expression.Parameter(typeof(TArg16));
			CompiledDelegate = (System.Linq.Expressions.Expression.Lambda<global::@FastGenericNew.FastNew.FastNewDelegate<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TArg14, TArg15, TArg16>>(IsValid
				? (System.Linq.Expressions.Expression)System.Linq.Expressions.Expression.New(CachedConstructor!, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15, p16)
				: (System.Linq.Expressions.Expression)System.Linq.Expressions.Expression.Call(global::@FastGenericNew.FastNewThrowHelper.GetSmartThrow<T>())
			, new System.Linq.Expressions.ParameterExpression[] { p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15, p16 })).Compile();
#else
			var dm = new DynamicMethod("", typeof(T), new Type[] { typeof(global::@FastGenericNew._FastNewDynMetClosure), typeof(TArg0), typeof(TArg1), typeof(TArg2), typeof(TArg3), typeof(TArg4), typeof(TArg5), typeof(TArg6), typeof(TArg7), typeof(TArg8), typeof(TArg9), typeof(TArg10), typeof(TArg11), typeof(TArg12), typeof(TArg13), typeof(TArg14), typeof(TArg15), typeof(TArg16) }, restrictedSkipVisibility: true);
			var il = dm.GetILGenerator(26);
			if (IsValid)
			{
				il.Emit(OpCodes.Ldarg_1);
				il.Emit(OpCodes.Ldarg_2);
				il.Emit(OpCodes.Ldarg_3);
				il.Emit(OpCodes.Ldarg_S, (byte)4);
				il.Emit(OpCodes.Ldarg_S, (byte)5);
				il.Emit(OpCodes.Ldarg_S, (byte)6);
				il.Emit(OpCodes.Ldarg_S, (byte)7);
				il.Emit(OpCodes.Ldarg_S, (byte)8);
				il.Emit(OpCodes.Ldarg_S, (byte)9);
				il.Emit(OpCodes.Ldarg_S, (byte)10);
				il.Emit(OpCodes.Ldarg_S, (byte)11);
				il.Emit(OpCodes.Ldarg_S, (byte)12);
				il.Emit(OpCodes.Ldarg_S, (byte)13);
				il.Emit(OpCodes.Ldarg_S, (byte)14);
				il.Emit(OpCodes.Ldarg_S, (byte)15);
				il.Emit(OpCodes.Ldarg_S, (byte)16);
				il.Emit(OpCodes.Ldarg_S, (byte)17);
				il.Emit(OpCodes.Newobj, CachedConstructor!);
			}
			else
			{
				il.Emit(OpCodes.Call, global::@FastGenericNew.FastNewThrowHelper.GetSmartThrow<T>());
			}
			il.Emit(OpCodes.Ret);
			CompiledDelegate = (global::@FastGenericNew.FastNew.FastNewDelegate<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TArg14, TArg15, TArg16>)dm.CreateDelegate(typeof(global::@FastGenericNew.FastNew.FastNewDelegate<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TArg14, TArg15, TArg16>), global::@FastGenericNew._FastNewDynMetClosure.Instance);
#endif
		}
	}
	internal static partial class FastNew<
#if NET5_0_OR_GREATER
[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors | DynamicallyAccessedMemberTypes.NonPublicConstructors)]
#endif
T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TArg14, TArg15, TArg16, TArg17>
	{
		/// <summary>
		/// The constructor of <typeparamref name="T" /> with given arguments. <br/>
		/// Could be <see langword="null" /> if the constructor couldn't be found.
		/// </summary>
		public static readonly ConstructorInfo? CachedConstructor = typeof(T).GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, null, new Type[]
		{
			typeof(TArg0),
			typeof(TArg1),
			typeof(TArg2),
			typeof(TArg3),
			typeof(TArg4),
			typeof(TArg5),
			typeof(TArg6),
			typeof(TArg7),
			typeof(TArg8),
			typeof(TArg9),
			typeof(TArg10),
			typeof(TArg11),
			typeof(TArg12),
			typeof(TArg13),
			typeof(TArg14),
			typeof(TArg15),
			typeof(TArg16),
			typeof(TArg17),
		}, null);
		public static readonly global::@FastGenericNew.FastNew.FastNewDelegate<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TArg14, TArg15, TArg16, TArg17> CompiledDelegate;

		public static readonly bool IsValid;

		static FastNew()
		{
			IsValid = CachedConstructor != null && !typeof(T).IsAbstract;
#if NETFRAMEWORK
			var p0 = System.Linq.Expressions.Expression.Parameter(typeof(TArg0));
			var p1 = System.Linq.Expressions.Expression.Parameter(typeof(TArg1));
			var p2 = System.Linq.Expressions.Expression.Parameter(typeof(TArg2));
			var p3 = System.Linq.Expressions.Expression.Parameter(typeof(TArg3));
			var p4 = System.Linq.Expressions.Expression.Parameter(typeof(TArg4));
			var p5 = System.Linq.Expressions.Expression.Parameter(typeof(TArg5));
			var p6 = System.Linq.Expressions.Expression.Parameter(typeof(TArg6));
			var p7 = System.Linq.Expressions.Expression.Parameter(typeof(TArg7));
			var p8 = System.Linq.Expressions.Expression.Parameter(typeof(TArg8));
			var p9 = System.Linq.Expressions.Expression.Parameter(typeof(TArg9));
			var p10 = System.Linq.Expressions.Expression.Parameter(typeof(TArg10));
			var p11 = System.Linq.Expressions.Expression.Parameter(typeof(TArg11));
			var p12 = System.Linq.Expressions.Expression.Parameter(typeof(TArg12));
			var p13 = System.Linq.Expressions.Expression.Parameter(typeof(TArg13));
			var p14 = System.Linq.Expressions.Expression.Parameter(typeof(TArg14));
			var p15 = System.Linq.Expressions.Expression.Parameter(typeof(TArg15));
			var p16 = System.Linq.Expressions.Expression.Parameter(typeof(TArg16));
			var p17 = System.Linq.Expressions.Expression.Parameter(typeof(TArg17));
			CompiledDelegate = (System.Linq.Expressions.Expression.Lambda<global::@FastGenericNew.FastNew.FastNewDelegate<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TArg14, TArg15, TArg16, TArg17>>(IsValid
				? (System.Linq.Expressions.Expression)System.Linq.Expressions.Expression.New(CachedConstructor!, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15, p16, p17)
				: (System.Linq.Expressions.Expression)System.Linq.Expressions.Expression.Call(global::@FastGenericNew.FastNewThrowHelper.GetSmartThrow<T>())
			, new System.Linq.Expressions.ParameterExpression[] { p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15, p16, p17 })).Compile();
#else
			var dm = new DynamicMethod("", typeof(T), new Type[] { typeof(global::@FastGenericNew._FastNewDynMetClosure), typeof(TArg0), typeof(TArg1), typeof(TArg2), typeof(TArg3), typeof(TArg4), typeof(TArg5), typeof(TArg6), typeof(TArg7), typeof(TArg8), typeof(TArg9), typeof(TArg10), typeof(TArg11), typeof(TArg12), typeof(TArg13), typeof(TArg14), typeof(TArg15), typeof(TArg16), typeof(TArg17) }, restrictedSkipVisibility: true);
			var il = dm.GetILGenerator(27);
			if (IsValid)
			{
				il.Emit(OpCodes.Ldarg_1);
				il.Emit(OpCodes.Ldarg_2);
				il.Emit(OpCodes.Ldarg_3);
				il.Emit(OpCodes.Ldarg_S, (byte)4);
				il.Emit(OpCodes.Ldarg_S, (byte)5);
				il.Emit(OpCodes.Ldarg_S, (byte)6);
				il.Emit(OpCodes.Ldarg_S, (byte)7);
				il.Emit(OpCodes.Ldarg_S, (byte)8);
				il.Emit(OpCodes.Ldarg_S, (byte)9);
				il.Emit(OpCodes.Ldarg_S, (byte)10);
				il.Emit(OpCodes.Ldarg_S, (byte)11);
				il.Emit(OpCodes.Ldarg_S, (byte)12);
				il.Emit(OpCodes.Ldarg_S, (byte)13);
				il.Emit(OpCodes.Ldarg_S, (byte)14);
				il.Emit(OpCodes.Ldarg_S, (byte)15);
				il.Emit(OpCodes.Ldarg_S, (byte)16);
				il.Emit(OpCodes.Ldarg_S, (byte)17);
				il.Emit(OpCodes.Ldarg_S, (byte)18);
				il.Emit(OpCodes.Newobj, CachedConstructor!);
			}
			else
			{
				il.Emit(OpCodes.Call, global::@FastGenericNew.FastNewThrowHelper.GetSmartThrow<T>());
			}
			il.Emit(OpCodes.Ret);
			CompiledDelegate = (global::@FastGenericNew.FastNew.FastNewDelegate<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TArg14, TArg15, TArg16, TArg17>)dm.CreateDelegate(typeof(global::@FastGenericNew.FastNew.FastNewDelegate<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TArg14, TArg15, TArg16, TArg17>), global::@FastGenericNew._FastNewDynMetClosure.Instance);
#endif
		}
	}
}
