//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by FastGenericNew.SourceGenerator
//     Please do not modify this file directly
// <auto-generated/>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Diagnostics.CodeAnalysis;
using System.Reflection;
using System.ComponentModel;

namespace @FastGenericNew
{
	public static partial class FastNew<T>
	{
		public static readonly ConstructorInfo? Constructor = typeof(T).GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, null, Type.EmptyTypes, null);
	}
	public static partial class FastNew<T, TArg0>
	{
		public static readonly ConstructorInfo? Constructor = typeof(T).GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, null, new Type[]
		{
			typeof(TArg0),
		}, null);
	}
	public static partial class FastNew<T, TArg0, TArg1>
	{
		public static readonly ConstructorInfo? Constructor = typeof(T).GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, null, new Type[]
		{
			typeof(TArg0),
			typeof(TArg1),
		}, null);
	}
	public static partial class FastNew<T, TArg0, TArg1, TArg2>
	{
		public static readonly ConstructorInfo? Constructor = typeof(T).GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, null, new Type[]
		{
			typeof(TArg0),
			typeof(TArg1),
			typeof(TArg2),
		}, null);
	}
	public static partial class FastNew<T, TArg0, TArg1, TArg2, TArg3>
	{
		public static readonly ConstructorInfo? Constructor = typeof(T).GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, null, new Type[]
		{
			typeof(TArg0),
			typeof(TArg1),
			typeof(TArg2),
			typeof(TArg3),
		}, null);
	}
	public static partial class FastNew<T, TArg0, TArg1, TArg2, TArg3, TArg4>
	{
		public static readonly ConstructorInfo? Constructor = typeof(T).GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, null, new Type[]
		{
			typeof(TArg0),
			typeof(TArg1),
			typeof(TArg2),
			typeof(TArg3),
			typeof(TArg4),
		}, null);
	}
	public static partial class FastNew<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5>
	{
		public static readonly ConstructorInfo? Constructor = typeof(T).GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, null, new Type[]
		{
			typeof(TArg0),
			typeof(TArg1),
			typeof(TArg2),
			typeof(TArg3),
			typeof(TArg4),
			typeof(TArg5),
		}, null);
	}
	public static partial class FastNew<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6>
	{
		public static readonly ConstructorInfo? Constructor = typeof(T).GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, null, new Type[]
		{
			typeof(TArg0),
			typeof(TArg1),
			typeof(TArg2),
			typeof(TArg3),
			typeof(TArg4),
			typeof(TArg5),
			typeof(TArg6),
		}, null);
	}
	public static partial class FastNew<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7>
	{
		public static readonly ConstructorInfo? Constructor = typeof(T).GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, null, new Type[]
		{
			typeof(TArg0),
			typeof(TArg1),
			typeof(TArg2),
			typeof(TArg3),
			typeof(TArg4),
			typeof(TArg5),
			typeof(TArg6),
			typeof(TArg7),
		}, null);
	}
	public static partial class FastNew<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8>
	{
		public static readonly ConstructorInfo? Constructor = typeof(T).GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, null, new Type[]
		{
			typeof(TArg0),
			typeof(TArg1),
			typeof(TArg2),
			typeof(TArg3),
			typeof(TArg4),
			typeof(TArg5),
			typeof(TArg6),
			typeof(TArg7),
			typeof(TArg8),
		}, null);
	}
	public static partial class FastNew<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9>
	{
		public static readonly ConstructorInfo? Constructor = typeof(T).GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, null, new Type[]
		{
			typeof(TArg0),
			typeof(TArg1),
			typeof(TArg2),
			typeof(TArg3),
			typeof(TArg4),
			typeof(TArg5),
			typeof(TArg6),
			typeof(TArg7),
			typeof(TArg8),
			typeof(TArg9),
		}, null);
	}
	public static partial class FastNew<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10>
	{
		public static readonly ConstructorInfo? Constructor = typeof(T).GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, null, new Type[]
		{
			typeof(TArg0),
			typeof(TArg1),
			typeof(TArg2),
			typeof(TArg3),
			typeof(TArg4),
			typeof(TArg5),
			typeof(TArg6),
			typeof(TArg7),
			typeof(TArg8),
			typeof(TArg9),
			typeof(TArg10),
		}, null);
	}
	public static partial class FastNew<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11>
	{
		public static readonly ConstructorInfo? Constructor = typeof(T).GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, null, new Type[]
		{
			typeof(TArg0),
			typeof(TArg1),
			typeof(TArg2),
			typeof(TArg3),
			typeof(TArg4),
			typeof(TArg5),
			typeof(TArg6),
			typeof(TArg7),
			typeof(TArg8),
			typeof(TArg9),
			typeof(TArg10),
			typeof(TArg11),
		}, null);
	}
	public static partial class FastNew<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12>
	{
		public static readonly ConstructorInfo? Constructor = typeof(T).GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, null, new Type[]
		{
			typeof(TArg0),
			typeof(TArg1),
			typeof(TArg2),
			typeof(TArg3),
			typeof(TArg4),
			typeof(TArg5),
			typeof(TArg6),
			typeof(TArg7),
			typeof(TArg8),
			typeof(TArg9),
			typeof(TArg10),
			typeof(TArg11),
			typeof(TArg12),
		}, null);
	}
	public static partial class FastNew<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13>
	{
		public static readonly ConstructorInfo? Constructor = typeof(T).GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, null, new Type[]
		{
			typeof(TArg0),
			typeof(TArg1),
			typeof(TArg2),
			typeof(TArg3),
			typeof(TArg4),
			typeof(TArg5),
			typeof(TArg6),
			typeof(TArg7),
			typeof(TArg8),
			typeof(TArg9),
			typeof(TArg10),
			typeof(TArg11),
			typeof(TArg12),
			typeof(TArg13),
		}, null);
	}
	public static partial class FastNew<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TArg14>
	{
		public static readonly ConstructorInfo? Constructor = typeof(T).GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, null, new Type[]
		{
			typeof(TArg0),
			typeof(TArg1),
			typeof(TArg2),
			typeof(TArg3),
			typeof(TArg4),
			typeof(TArg5),
			typeof(TArg6),
			typeof(TArg7),
			typeof(TArg8),
			typeof(TArg9),
			typeof(TArg10),
			typeof(TArg11),
			typeof(TArg12),
			typeof(TArg13),
			typeof(TArg14),
		}, null);
	}
	public static partial class FastNew<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TArg14, TArg15>
	{
		public static readonly ConstructorInfo? Constructor = typeof(T).GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, null, new Type[]
		{
			typeof(TArg0),
			typeof(TArg1),
			typeof(TArg2),
			typeof(TArg3),
			typeof(TArg4),
			typeof(TArg5),
			typeof(TArg6),
			typeof(TArg7),
			typeof(TArg8),
			typeof(TArg9),
			typeof(TArg10),
			typeof(TArg11),
			typeof(TArg12),
			typeof(TArg13),
			typeof(TArg14),
			typeof(TArg15),
		}, null);
	}
}
