namespace FastGenericNew.SourceGenerator;

public readonly partial record struct GeneratorOptions
{
    [GeneratorOption(16)]
    public int MaxParameterCount { get; init; }

    [GeneratorOption(false)]
    public bool PublicFastNewCore { get; init; }

    [GeneratorOption(true)]
    public bool GenerateTryCreateInstance { get; init; }

    [GeneratorOption(true)]
    public bool GenerateCreateInstance { get; init; }

    [GeneratorOption(true)]
    public bool GenerateTypeCreateInstance { get; init; }

    [GeneratorOption(true)]
    public bool NonPublicConstructorSupport { get; init; }

    [GeneratorOption("FastGenericNew")]
    public string Namespace { get; init; }

    [GeneratorOption(false)]
    public bool ForceFastNewDelegate { get; init; }

    [GeneratorOption(true)]
    public bool AlertGeneratedFile { get; init; }

    [GeneratorOption(false)]
    public bool PrettyOutput { get; init; }

    [GeneratorOption(false)]
    public bool OutputGenerationInfo { get; init; }

    [GeneratorOption(false, PresentPreProcessor = true)]
    public bool AllowUnsafeImplementation { get; init; }

    [GeneratorOption(false)]
    public bool PublicFastNew { get; init; }

    // ctor will be generated by InternalGenerator
    //public GeneratorOptions(AnalyzerConfigOptionsProvider? provider)

    public readonly string GlobalNSDot() => string.IsNullOrWhiteSpace(Namespace)
        ? "global::@"
        : $"global::@{Namespace}.";

    public readonly string DynamicallyAccessedMembers(int argumentCount)
    {
        bool noArguments = argumentCount == 0;
        return NonPublicConstructorSupport
            ? noArguments
                ? "[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicParameterlessConstructor | DynamicallyAccessedMemberTypes.NonPublicConstructors)]"
                : "[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors | DynamicallyAccessedMemberTypes.NonPublicConstructors)]"
            : noArguments
                ? "[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicParameterlessConstructor)]"
                : "[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)]";
    }

    public readonly string PreCondition(string optionName) => $"{CodeBuilder.Const_PreProcessDefinePrefix}{optionName}";
}
