namespace FastGenericNew.SourceGenerator.Utilities;

partial struct CodeBuilder
{
    public void WriteFileHeader()
    {
        if (Options.AlertGeneratedFile)
            AppendLine(
@"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by FastGenericNew.SourceGenerator
//     Please do not modify this file directly
// <auto-generated/>
//------------------------------------------------------------------------------");

        _Write_PreProcessorDefinitions();
        AppendLine("#nullable enable");

        AppendLine(@"using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Diagnostics.CodeAnalysis;
using System.Reflection;
using System.Reflection.Emit;
using System.ComponentModel;
");
    }

    public void GlobalNamespaceDot()
    {
        if (string.IsNullOrWhiteSpace(Options.Namespace)) return;
        Append("global::@");
        Append(Options.Namespace);
        Append('.');
    }

    private partial void _Write_PreProcessorDefinitions();
}
